src/Entity/Pdf.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PdfRepository")
 * @Vich\Uploadable
 */
class Pdf
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $pdf;

    /**
     * @Vich\UploadableField(mapping="article_pdfs", fileNameProperty="pdf")
     * @var File
     * @Assert\File(
     *     maxSize = "64000000",
     *     mimeTypes = {"application/pdf", "application/x-pdf"},
     *     mimeTypesMessage = "Votre fichier n'est pas un pdf",
     *     maxSizeMessage = "Votre fichier est trop gros ({{ size }}Mo). La taille maximum autorisée est : {{ limit }}Mo"
     * )
     */
    private $pdfFile;

    public function getId()
    {
        return $this->id;
    }

    public function setPdfFile(File $pdf = null)
    {
        $this->pdfFile = $pdf;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($pdf) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getPdfFile()
    {
        return $this->pdfFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getPdf()
    {
        return $this->pdf;
    }

    public function setPdf($pdf)
    {
        $this->pdf = $pdf;

        return $this;
    }
    
    public function getAbsolutePath()
    {
        return 'uploads/articles/pdfs/'.$this->getPdf();
    }
}

templates/index/article.html.twig
{% extends "base.html.twig" %}

{% block title_fb %}
	{{ article.title }} - {{ parent() }}
{% endblock %}

{% block image_fb %}
	{% if article.image %}{{ article.image.absolutePath | imagine_filter('compression') }}
	{% else %}{{ parent() }}{% endif %}
{% endblock %}

{% block desc_fb %}
	{{ article.text|striptags }}
{% endblock %}

{% block title %}
	{{ article.title }} - {{ parent() }}
{% endblock %}

{% block body %}

	<div>
		{% set mois = {01:"Janvier", 02:"Février", 03:"Mars", 04:"Avril", 05:"Mai", 06:"Juin", 07:"Juillet", 08:"Août", 09:"Septembre", 10:"Octobre", 11:"Novembre", 12:"Décembre"} %}
<!-- 		<div class="text_article">
			<div class="news_title"><span style="font-weight:bold;color:#018EB2">article</span><span style="font-weight:bold;font-size:0.9em;color:#c9c9c9"> / {{ article.date|date("d") }} {{ mois[article.date|date("m")|round] }} {{ article.date|date("Y") }}</span></div> 
			<p>{{ article.text }}</p>
			<div class="fb-like" data-href="{{ app.request.uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
		</div> -->	
		<div class="text_article">
			<div class="Article-header">
				<h1 style="line-height:1.5em;color:white;margin:0 auto 1rem auto;font-size:1.5em;">{{ article.title }}</h2>
				{% if article.image %}
				<div style="border:2px solid white;width:15vw;margin:0em auto 1rem auto;height:15vw;overflow:hidden;border-radius:50%">
					<img src="{{ asset(article.image.absolutePath | imagine_filter('miniature')) }}" style="width:100%;height:100%;-o-object-fit:cover;object-fit:cover;" id="image"/>
				</div>
				{% endif %}				
				<div style="margin:auto">						
					<span style="color:white;margin-right:1em;line-height:1em">Publié le {{ article.date|date("d") }} {{ mois[article.date|date("m")|round] }} {{ article.date|date("Y") }}</span>			
					<div class="fb-like" data-href="{{ app.request.getSchemeAndHttpHost() }}{{ app.request.pathinfo }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
				</div>
			</div>		
			<div style="box-shadow: -7px -7px 38px -12px rgba(0,0,0,0.75);margin:1em 0 1em 0;background: #fafafa;margin: 1em 0 1em 0;padding: 1em;">
				{{ article.text|raw }}
				<div class="Article-pdfBlock">
					{% for pdf in article.pdfs %}
						<a class="Article-pdf" href="{{ asset(pdf.absolutePath) }}" download="{{ pdf.pdf }}"><span class="icon-file-pdf"></span> {{ pdf.pdf }}</a>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block javascripts %}
	<script>
		(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.7&appId=204087879970953";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	</script>
{% endblock %}

templates/index/consent_cookie.html.twig
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "rgba(239, 239, 239, 0.9);",
      "text": "#414141"
    },
    "button": {
      "background": "transparent",
      "text": "#03cbff",
      "border": "#03cbff"
    }
  },
  "content": {
    "message": "En poursuivant votre navigation, vous acceptez l’utilisation de cookies.",
    "dismiss": "J'accepte !",
    "link": "En savoir plus"
  }
})});
</script>

templates/index/decouvrir.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Découvrir - {{ parent() }}
{% endblock %}

{% block body %}

	<div>
		<div class="block_decouvrir">
			<div class="text_decouvrir">
				<div>
					<h2>Son histoire</h2>
					<span>
						Le club d'aviron Saintais fut créé en 1862. Situé au bord de la Charente, il offre aux rameurs un cadre idéal.<br />
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Il comporte plus d'une centaine de licenciés annuels et constitue une association de loi 1901 affiliée à la Fédération Française d'Aviron.<br />
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Celui-ci bénéficie du titre d'École française d'aviron 3 étoiles.
					</span>
				</div>
			</div>
			<div class="image_decouvrir"><img style="width:100%" src="{{asset('img/decouvrir1.jpg')}}"/>
			</div>
		</div>
		<div class="block_decouvrir">
			<div class="text_decouvrir">
				<div>
					<h2>Son fonctionnement</h2>
					<span>
						L'aviron est accessible aux compétiteurs comme aux personnes recherchant une pratique exclusivement loisir.<br />
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;L’âge minimum requis est de 11 ans et pour une première inscription pour les mineurs il convient de présenter un brevet de natation de 25m minimum, et chaque catégorie dispose de ses propres horaires d’entrainement encadrées par un entraineur qualifié..
					</span>
				</div>
			</div>
			<div class="image_decouvrir"><img style="width:100%" src="{{asset('img/decouvrir2.jpg')}}"/>
			</div>
		</div>
		<div class="block_decouvrir" id="targetCompetiteur">
			<div class="text_decouvrir">
				<div>
					<h2>Ses compétiteurs</h2>
					<span>
						L'effectif des compétiteurs avoisine la centaine de personnes. Il se divise en plusieurs catégories s'entrainant et participant ensemble aux diverses régates.<br />
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;La pratique de la compétition est accessible à tout âge et permet de s'essayer dans chacune des différentes formes de ce sport : aviron en individuel ou collectif (de 1 à 8 rameurs), aviron indoor (ergométre), musculation...<br />
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Les déplacements à travers la France sont nombreux au cours de l'année et permettent aux rameurs de se donner des objectifs et de progresser ensemble.
					</span>
				</div>
			</div>
			<div class="image_decouvrir"><img style="width:100%" src="{{asset('img/decouvrir3.jpg')}}"/>
			</div>
		</div>	
		<div class="block_decouvrir" id="targetLoisir">
			<div class="text_decouvrir">
				<div>
					<h2>Ses loisirs</h2>
					<span>
						Accessible à toutes personnes cherchant à garder une activité physique complète sans porter de but premier à la compétition.<br />
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;L'engagement général du groupe permet de rester motivé et de se faire plaisir tout au long de l'année.<br />
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Les Randon'Aviron viennent compléter cette pratique avec des sorties ponctuelles s'étendant sur des journées entières et permettant de découvrir le patrimoine français d'une nouvelle manière.<br />
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;L'aviron saintais possède sa propre randonnée, la Saintongeaise comprenant un allez-retour à St-Savinien avec une halte repas dans un cadre champêtre.
					</span>
				</div>
			</div>
			<div class="image_decouvrir"><img style="width:100%" src="{{asset('img/decouvrir4.jpg')}}"/>
			</div>
		</div>
	</div>
	
{% endblock %}

templates/index/galerie.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Galerie - {{ parent() }}
{% endblock %}

{% block body %}
	<span id="first_pagination">{{ knp_pagination_render(pagination) }}</span>
	<div id="galerie"><img src="{{asset('img/loader.gif')}}" style="display:block;width:100px;margin:auto" id="loader"/></div>
	<span id="last_pagination">{{ knp_pagination_render(pagination) }}</span>
{% endblock %}

{% block javascripts %}
	<script src="{{ asset('js/galerie.js') }}"></script>
{% endblock %}

templates/index/legal.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Mentions légales - {{ parent() }}
{% endblock %}

{% block body %}
	<div class="text_article">
		<h2>Mentions légales</h2><br/>
		<span>
		<strong>Club d'Aviron Saintais</strong><br/>
		6 Rue de Courbiac<br/>
		17100 Saintes<br/>
		France<br/>
		Téléphone : 05 46 74 01 66
		</span><br/><br/>
		<span>
		Le site www.aviron-saintais.fr est hébergé chez OVH.<br/>
		2 rue Kellermann<br/>
		59100 Roubaix<br/>
		France
		</span>
	</div>
{% endblock %}

templates/index/list.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Articles - {{ parent() }}
{% endblock %}

{% block body %}
	<div>
	 <span id="first_pagination">{{ knp_pagination_render(pagination) }}</span>
		{% set mois = {01:"janv", 02:"févr", 03:"mars", 04:"avr", 05:"mai", 06:"juin", 07:"juill", 08:"août", 09:"sept", 10:"oct", 11:"nov", 12:"déc"} %}
		{% for article in pagination %}
			<div class="block_article"><a href="{{ path('article', {'id': article.id}) }}">
				<div class="block_article_text">
					<div class="news_title">
						<span style="font-weight:bold;color:#018EB2">article</span><span style="font-weight:bold;font-size:0.9em;color:#c9c9c9"> / {{ article.date|date("d") }} {{ mois[article.date|date("m")|round] }} {{ article.date|date("Y") }}</span>
						<h4 style="font-weight:bold;">{{ article.title }}</h4>
					</div>
					<span>{{ article.text|striptags|truncate(280, true, '...')|raw }}</span>
				</div>
				<div>{% if article.image %}<img style="width:100%;height:100%" src="{{ article.image.absolutePath | imagine_filter('miniature') }}">{% endif %}</div>
			</a></div>
		{% endfor %}
	 {{ knp_pagination_render(pagination) }}
	 </div>
{% endblock %}